rabbitmq:
  image: rabbitmq:management
  ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
  environment:
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_VHOST=/
    - RABBITMQ_MANAGEMENT_USER=guest
    - RABBITMQ_MANAGEMENT_PASSWORD=guest