# settings.py
AMQP_INBOUND_QUEUE = 'test'
AMQP_OUTBOUND_EXCHANGE = 'pubsub'
AMQP_USERNAME='guest'
AMQP_PASSWORD='guest'
AMQP_INBOUND_QUEUE_DURABLE=True
AMQP_OUTBOUND_EXCHANGE_TYPE='fanout'
AMQP_OUTBOUND_EXCHANGE_DURABLE=False
AMQP_INBOUND_EXCHANGE='pubsub'